<a href="https://colab.research.google.com/github/msjun23/Deep-Learning-from-Scratch/blob/main/Chapter3/n_dimentional_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

넘파이의 다차원 배열을 사용한 계산법을 숙달하면 신경망을 효율적으로 구현할 수 있다.

#다차원 배열
기본은 '숫자의 집합'이다. 2, 3, N차원으로 나열하는 것을 통틀어 다차원 배열이라고 한다.

In [1]:
# 1차원 배열
import numpy as np

A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))   # np.ndim() 함수로 배열의 차원 수 확인 가능
print(A.shape)      # 배열의 형상은 shape로 확인 가능. 반환형은 튜플
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [3]:
# 2차원 배열 = 행렬(matrix)
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [5]:
# 행렬의 곱 구현
A = np.array([[1, 2], [3, 4]])
print(A.shape)
B = np.array([[5, 6], [7, 8]])
print(B.shape)

print(np.dot(A, B))   # np.dot() 함수를 이용해 행렬의 곱 계산 가능

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


In [6]:
# 2x3 행렬과 3x2 행렬의 곱 구현
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)
B = np.array([[1, 2], [3, 4,], [5, 6]])
print(B.shape)

print(np.dot(A, B))   # (2, 3), (3, 2)행렬의 곱 결과는 (2, 2)

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


In [7]:
# 2x3 행렬과 2x2 행렬의 곱은 계산할 수 없다.
C = np.array([[1, 2], [3, 4]])
print(C.shape)
print(A.shape)

print(np.dot(A, C))

(2, 2)
(2, 3)


ValueError: ignored

In [11]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
print(A.shape)
B = np.array([7, 8])
print(B)
print(B.shape)

print(np.dot(A, B))

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[7 8]
(2,)
[23 53 83]


In [12]:
# 신경망에서의 행렬곱
# X(입력), W(가중치)의 대응하는 차원의 원소 수가 같아야 한다.
X = np.array([1, 2])
print(X)
print(X.shape)
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)
print(W.shape)

Y = np.dot(X, W)
print(Y)

[1 2]
(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]
