<a href="https://colab.research.google.com/github/msjun23/Deep-Learning-from-Scratch/blob/main/Chapter1/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**넘파이**의 배열 클래스인 numpy.array를 사용하여 배열이나 행렬 계산을 수행한다.

In [1]:
import numpy as np

np.array()는 파이썬의 리스트를 인수로 받아 넘파이 라이브러리가 제공하는 특수한 형태의 배열(numpy.ndarray)을 반환한다.

In [2]:
x = np.array([1.0, 2.0, 3.0]) # 1차원 배열 생성
print(x)
print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)    # 원소별 덧셈
print(x - y)
print(x * y)    # 원소별 곱셈
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


두 배열 x, y의 원소들을 가지고 산술 연산을 진행하였다. 이때 주의할 점은 두 배열의 원소 수가 같다는 것이다. 두 배열의 원소 수가 같다면, 산술 연산은 각 원소에 대해 행해진다. 반면, 원소 수가 다를 경우에는 오류가 발생한다.

'원소별'이라는 말은 element-wise 라고 한다. 예를 들어 '원소별 곱셈'은 element-wise product라고 한다.

넘파이 배열은 원소별 계산뿐 아니라 넘파이 배열과 스칼라값의 조합으로 된 산술 연산도 수행할 수 있다. 이 경우 스칼라값과의 계산이 넘파이 배열 원소별로 수행되는데 이를 **브로트캐스트**라고 한다.

In [4]:
x = np.array([1.0, 2.0, 3.0])
print(x / 2.0)

[0.5 1.  1.5]


넘파이 배열은 1차원 배열 뿐 아니라 다차원 배열 작성에도 유용하다.

In [5]:
A = np.array([[1, 2], [3, 4]])    # 2차원 배열 생성
print(A)
print(A.shape)    # A의 크기(형태)
print(A.dtype)    # A의 데이터 타입

[[1 2]
 [3 4]]
(2, 2)
int64


In [6]:
B = np.array([[3, 0], [0, 6]])
print(A + B)
print(A * B)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


차원(형상)이 같은 행렬의 대응하는 원소별로 산술 연산도 가능하다. 행렬과 스칼라값의 산술 연산도 가능하고, 이때도 배열과 마찬가지로 **브로트캐스트** 기능이 작동한다.

In [7]:
print(A)
print(A * 10)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


# 브로드캐스트

넘파이에서는 형상이 다른 배열끼리도 계산할 수 있다. 앞의 예에서 2 x 2 행렬과 스칼라값을 곱했다. 이때 스칼라값을 2 x 2 행렬로 확대한 한 대응하는 원소별 연산이 이루어진 것이다. 이러한 기능을 **브로트캐스트**라고 한다.

아래의 예제는 1차원 배열인 B가 2차원 배열로 변형된 후 연산이 이루어진다.

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print(A * B)

[[10 40]
 [30 80]]


원소의 인덱스는 당연히 0부터 시작하고, for 문으로도 원소의 접근이 가능하다.

In [9]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print(X[0])    # 0행
print(X[0][1])    # 0행 1열

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55


In [10]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


넘파이는 이외에도, 인덱스를 배열로 지정해 한 번에 여러 원소에 접근할 수도 있다.

In [11]:
X = X.flatten()   # X를 1차원 배열로 변환(평탄화)
print(X)
print(X[np.array([0, 2, 4])])   # 인덱스가 0, 2, 4인 원소 얻기
print(X[([0, 2, 4])])

[51 55 14 19  0  4]
[51 14  0]
[51 14  0]


특정 조건을 만족하는 원소만 얻을 수도 있다.

In [12]:
print(X > 15)   # X의 원소 중 15보다 큰 것들 반환, 출력
print(X[X > 15])    # X의 원소 중 15보다 큰 것들 반환 -> 인덱스로 사용

[ True  True False  True False False]
[51 55 19]
